@extends('control.layout')
@section('title', $tenant->name)
@section('heading', $tenant->name)
@section('content')
<div class="card"><div class="row between"><div><span class="badge {{ $tenant->status }}">{{ $tenant->status }}</span> <span class="muted">ID <span class="code">{{ $tenant->id }}</span> · schema {{ $tenant->schema_version }}</span></div></div>
<form method="post" action="{{ route('control.tenants.status', $tenant) }}">@csrf @method('PUT')<input type="hidden" name="version" value="{{ $tenant->version }}"><div class="fields"><div><label>Status</label><select name="status"><option value="active">active</option><option value="suspended">suspended</option><option value="archived">archived</option></select></div><div><label>Reason (required for suspension/archive)</label><input name="reason"></div></div><p><button class="btn warn">Apply status change</button></p></form></div>

<div class="card"><h2 class="section-title">Domains</h2><table><thead><tr><th>Host</th><th>Primary</th><th>Verification</th><th></th></tr></thead><tbody>@forelse($tenant->domains as $domain)<tr><td class="code">{{ $domain->normalized_host }}</td><td>{{ $domain->is_primary ? 'Yes' : 'No' }}</td><td><span class="badge {{ $domain->verified_at ? 'verified' : '' }}">{{ $domain->verified_at ? 'verified' : 'unverified' }}</span></td><td>@if(!$domain->verified_at)<form method="post" action="{{ route('control.domains.verify', $domain) }}">@csrf<button class="btn secondary">Mark verified</button></form>@endif</td></tr>@empty<tr><td colspan="4" class="muted">No domains.</td></tr>@endforelse</tbody></table>
<form method="post" action="{{ route('control.tenants.domains.store', $tenant) }}">@csrf<div class="fields"><div><label>Hostname only</label><input name="host" placeholder="customer.example.com" required></div><div class="row"><label><input style="width:auto" type="checkbox" name="is_primary" value="1"> Primary</label><label><input style="width:auto" type="checkbox" name="verified" value="1"> DNS already verified</label></div></div><p><button class="btn">Add domain</button></p></form></div>

<div class="card"><h2 class="section-title">Tenant database</h2>@if($tenant->databaseConfiguration)<p class="muted">Stored credentials are encrypted and never displayed. Database: <span class="code">{{ $tenant->databaseConfiguration->database_name }}</span>; last test: {{ $tenant->databaseConfiguration->last_connection_test_at ?: 'never' }} ({{ $tenant->databaseConfiguration->last_connection_succeeded === true ? 'passed' : ($tenant->databaseConfiguration->last_connection_succeeded === false ? 'failed' : 'not tested') }})</p>@endif
<form method="post" action="{{ route('control.tenants.database', $tenant) }}">@csrf @method('PUT')<div class="fields">
<div><label>Allowed DB host</label><input name="host" value="{{ old('host', $tenant->databaseConfiguration?->host ?: '127.0.0.1') }}" required></div><div><label>Port</label><input type="number" name="port" value="{{ old('port', $tenant->databaseConfiguration?->port ?: 3306) }}" required></div>
<div><label>Database name</label><input name="database_name" value="{{ old('database_name', $tenant->databaseConfiguration?->database_name) }}" required></div><div><label>Runtime username</label><input name="username" value="{{ old('username', $tenant->databaseConfiguration?->username) }}" required></div>
<div><label>{{ $tenant->databaseConfiguration ? 'New runtime password (blank keeps current)' : 'Runtime password' }}</label><input type="password" name="password" autocomplete="new-password"></div><div><label>Migration username (optional)</label><input name="migration_username" value="{{ old('migration_username', $tenant->databaseConfiguration?->migration_username) }}"></div>
<div><label>New migration password</label><input type="password" name="migration_password" autocomplete="new-password"></div></div><p class="row"><button class="btn">Save encrypted credentials</button></p></form>
@if($tenant->databaseConfiguration)<form method="post" action="{{ route('control.tenants.database.test', $tenant) }}">@csrf<button class="btn secondary">Test exact connection</button></form>@endif</div>

@endsection
