@extends('control.layout')
@section('title', $tenant->name)
@section('heading', $tenant->name)
@section('content')
<div class="card"><div class="row between"><div><span class="badge {{ $tenant->status }}">{{ $tenant->status }}</span> <span class="muted">ID <span class="code">{{ $tenant->id }}</span> · schema {{ $tenant->schema_version }}</span></div></div>
<form method="post" action="{{ route('control.tenants.status', $tenant) }}">@csrf @method('PUT')<input type="hidden" name="version" value="{{ $tenant->version }}"><div class="fields"><div><label>Status</label><select name="status"><option value="active">active</option><option value="suspended">suspended</option><option value="archived">archived</option></select></div><div><label>Reason (required for suspension/archive)</label><input name="reason"></div></div><p><button class="btn warn">Apply status change</button></p></form></div>

<div class="card"><h2 class="section-title">Domains</h2><table><thead><tr><th>Host</th><th>Primary</th><th>Verification</th><th></th></tr></thead><tbody>@forelse($tenant->domains as $domain)<tr><td class="code">{{ $domain->normalized_host }}</td><td>{{ $domain->is_primary ? 'Yes' : 'No' }}</td><td><span class="badge {{ $domain->verified_at ? 'verified' : '' }}">{{ $domain->verified_at ? 'verified' : 'unverified' }}</span></td><td>@if(!$domain->verified_at)<form method="post" action="{{ route('control.domains.verify', $domain) }}">@csrf<button class="btn secondary">Mark verified</button></form>@endif</td></tr>@empty<tr><td colspan="4" class="muted">No domains.</td></tr>@endforelse</tbody></table>
<form method="post" action="{{ route('control.tenants.domains.store', $tenant) }}">@csrf<div class="fields"><div><label>Hostname only</label><input name="host" placeholder="customer.example.com" required></div><div class="row"><label><input style="width:auto" type="checkbox" name="is_primary" value="1"> Primary</label><label><input style="width:auto" type="checkbox" name="verified" value="1"> DNS already verified</label></div></div><p><button class="btn">Add domain</button></p></form></div>

<div class="card"><h2 class="section-title">Tenant database</h2>@if($tenant->databaseConfiguration)<p class="muted">Stored credentials are encrypted and never displayed. Database: <span class="code">{{ $tenant->databaseConfiguration->database_name }}</span>; last test: {{ $tenant->databaseConfiguration->last_connection_test_at ?: 'never' }} ({{ $tenant->databaseConfiguration->last_connection_succeeded === true ? 'passed' : ($tenant->databaseConfiguration->last_connection_succeeded === false ? 'failed' : 'not tested') }})</p>@endif
<form method="post" action="{{ route('control.tenants.database', $tenant) }}">@csrf @method('PUT')<div class="fields">
<div><label>Allowed DB host</label><input name="host" value="{{ old('host', $tenant->databaseConfiguration?->host ?: '127.0.0.1') }}" required></div><div><label>Port</label><input type="number" name="port" value="{{ old('port', $tenant->databaseConfiguration?->port ?: 3306) }}" required></div>
<div><label>Database name</label><input name="database_name" value="{{ old('database_name', $tenant->databaseConfiguration?->database_name) }}" required></div><div><label>Runtime username</label><input name="username" value="{{ old('username', $tenant->databaseConfiguration?->username) }}" required></div>
<div><label>{{ $tenant->databaseConfiguration ? 'New runtime password (blank keeps current)' : 'Runtime password' }}</label><input type="password" name="password" autocomplete="new-password"></div><div><label>Migration username (optional)</label><input name="migration_username" value="{{ old('migration_username', $tenant->databaseConfiguration?->migration_username) }}"></div>
<div><label>New migration password</label><input type="password" name="migration_password" autocomplete="new-password"></div></div><p class="row"><button class="btn">Save encrypted credentials</button></p></form>
@if($tenant->databaseConfiguration)<form method="post" action="{{ route('control.tenants.database.test', $tenant) }}">@csrf<button class="btn secondary">Test exact connection</button></form>@endif</div>

<div class="card"><h2 class="section-title">Subscriptions</h2><table><thead><tr><th>Plan</th><th>Status</th><th>Period</th><th>Amount</th></tr></thead><tbody>@forelse($tenant->subscriptions as $subscription)<tr><td>{{ $subscription->plan?->name }}</td><td>{{ $subscription->status }}</td><td>{{ $subscription->starts_at->toDateString() }} → {{ $subscription->ends_at->toDateString() }}</td><td>{{ $subscription->currency }} {{ $subscription->agreed_amount }}</td></tr>@empty<tr><td colspan="4" class="muted">No subscription.</td></tr>@endforelse</tbody></table>
<form method="post" action="{{ route('control.tenants.subscriptions.store', $tenant) }}">@csrf<div class="fields"><div><label>Plan</label><select name="plan_id" required>@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }}</option>@endforeach</select></div><div><label>Amount</label><input type="number" step="0.01" min="0" name="agreed_amount" required></div><div><label>Starts</label><input type="date" name="starts_at" value="{{ now()->toDateString() }}" required></div><div><label>Ends</label><input type="date" name="ends_at" value="{{ now()->addMonth()->toDateString() }}" required></div><div><label>Grace ends</label><input type="date" name="grace_ends_at"></div><div><label>Currency</label><input name="currency" value="PKR" maxlength="3" required></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><p><button class="btn">Record subscription</button></p></form></div>

<div class="card"><h2 class="section-title">Manual payment ledger</h2><table><thead><tr><th>Date</th><th>Reference</th><th>Amount</th><th>Method</th><th></th></tr></thead><tbody>@php($payments = $tenant->subscriptions->flatMap->payments->sortByDesc('paid_at'))@forelse($payments as $payment)<tr><td>{{ $payment->paid_at }}</td><td>{{ $payment->reference }}</td><td>{{ $payment->currency }} {{ $payment->amount }}</td><td>{{ $payment->method }}</td><td>@if(!$payment->reversal_of_id && !$payments->contains('reversal_of_id', $payment->id))<form method="post" action="{{ route('control.payments.reverse', $payment) }}">@csrf<input name="notes" placeholder="Reversal reason" required><button class="btn danger">Append reversal</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="muted">No payment records.</td></tr>@endforelse</tbody></table>
@if($tenant->subscriptions->isNotEmpty())<form method="post" action="{{ route('control.tenants.payments.store', $tenant) }}">@csrf<div class="fields"><div><label>Subscription</label><select name="subscription_id">@foreach($tenant->subscriptions as $subscription)<option value="{{ $subscription->id }}">{{ $subscription->plan?->name }} — {{ $subscription->ends_at->toDateString() }}</option>@endforeach</select></div><div><label>Amount</label><input type="number" step="0.01" min="0.01" name="amount" required></div><div><label>Reference</label><input name="reference"></div><div><label>Paid at</label><input type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></div><div><label>Method</label><input name="method" placeholder="bank transfer / cash"></div><div><label>Currency</label><input name="currency" value="PKR" maxlength="3" required></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><p><button class="btn">Append payment</button></p></form>@endif</div>
@endsection
